sonar.organization=contrastguy
sonar.projectKey=contrastguy_repoyard-cargo
sonar.sources=src
sonar.exclusions=src/**/*.test.ts
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
