apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cargo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: cargo
    newName: ghcr.io/contrastguy/repoyard-cargo
    newTag: sha-30ffc4b
configMapGenerator:
  - name: cargo-version
    literals:
      - GIT_SHA=30ffc4be375104fbd914af07c905f37246ca3161
