apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cargo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: cargo
    newName: ghcr.io/contrastguy/repoyard-cargo
    newTag: sha-e115f20
configMapGenerator:
  - name: cargo-version
    literals:
      - GIT_SHA=e115f201b42c04203d6490ebba7fdf35afd0e647
