apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cargo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: cargo
    newName: ghcr.io/contrastguy/repoyard-cargo
    newTag: sha-dd4d903
configMapGenerator:
  - name: cargo-version
    literals:
      - GIT_SHA=dd4d903d0f1057816fb81a1738e76d7750b50454
